# Generated by Django 2.2.24 on 2021-08-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0003_auto_20210813_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='le numéro de télephone doit avoir 9 chiffres', null=True, unique=True),
        ),
    ]
