# Generated by Django 2.2.24 on 2021-08-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0004_auto_20210816_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nom_site_evangelisation',
            field=models.CharField(help_text='le nom du site doit avoir au moins 03 caractères', max_length=200, unique=True, verbose_name="site d'évangélisation"),
        ),
    ]
