# Generated by Django 2.2.24 on 2021-08-17 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0005_auto_20210816_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evangelisation',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name="Jour d'évangélisation"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='ajouter une photo', null=True, upload_to='images/profile/%Y/'),
        ),
    ]
