# Generated by Django 2.2.24 on 2021-08-17 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0008_auto_20210817_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='boss',
            field=models.ManyToManyField(help_text='selectionner les personnes ayant évangelisés cette personne', related_name='personnes', to=settings.AUTH_USER_MODEL, verbose_name="Qui l'ont évangelisé ?"),
        ),
    ]
